### ISSUE TITLE
Implement routes for APIs

### ISSUE THREAD

**Issue by danpersa** [zalando/innkeeper#174]
The path is marked that it should end with a star. Here is how the path predicate will look like: `Path("/uri/*_")`

**Comment by danpersa** [comment]
I would keep the initial constraint that the `*` routes should start with `/api`.

**Comment by danpersa** [comment]
I think `*` routes should generate 2 skipper routes, one with `Path("/api/*_")` and one with `Path("/api")`. This is how we usually use them for APIs.

**Comment by NorthFury** [comment]
I will add the extra route generation.

Regarding the `/api` constraint, I can add a validation that the uri needs to match a configured pattern.

**Comment by danpersa** [comment]
👍 a configurable pattern/list of patterns would be great

**Comment by NorthFury** [comment]
After considering the implications of generating the extra virtual route, we decided to add some extra features to skipper that will allow us to only have one route.
